-- ============================================================
-- TableSmart - Insertion dans le catalogue Atlas Studio
-- Schema strictement aligne sur les autres apps (Advist, Liass'Pilot)
-- ============================================================

INSERT INTO public.apps (
  id,
  name,
  type,
  tagline,
  description,
  features,
  categories,
  pricing,
  pricing_period,
  color,
  icon,
  highlights,
  external_url,
  status,
  sort_order
)
VALUES (
  'tablesmart',
  'TableSmart',
  'App',
  'Digitalisation complète pour la restauration',
  'Plateforme SaaS tout-en-un pour restaurants, bars, hôtels et food courts. Du QR code client au KDS cuisine, en passant par les paiements Mobile Money — TableSmart digitalise toute la chaîne de service avec l''écosystème africain en tête. Square POS coûte 60 $/mois — TableSmart est 2x moins cher avec Mobile Money natif et conformité SYSCOHADA/DGI.',
  ARRAY[
    'Menu digital QR code (15 layouts premium)',
    'Commande client sans installation app',
    'Paiement Mobile Money (Orange Money, Wave, MTN, M-Pesa, Airtel)',
    'Paiement carte bancaire (Visa, Mastercard, Stripe)',
    'Paiement espèces avec rendu monnaie',
    'Split bill (égal, par item, montant custom)',
    'Pourboire ajustable (5 / 10 / 15 % ou libre)',
    'Cartes cadeaux & abonnements repas',
    'KDS cuisine temps réel (urgence chromatique)',
    'Validation item par item & boutons 64px',
    'Rupture stock cascade (menu + serveur + client)',
    'Filtre par poste (chaud/froid/grill/bar/pâtisserie)',
    'Mode rush (seuils réduits automatiquement)',
    'App serveur (plan de salle, notifications)',
    'Commandes manuelles & saisie verbale',
    'Notifications push staff (12 types prioritisés)',
    'App barman (tabs, bottle service, happy hour)',
    'App hôtesse (réservations, file d''attente, check-in)',
    'Console manager (service, stocks, rapports)',
    'Console propriétaire (finances, clients, fiscalité)',
    'Console SuperAdmin (multi-tenant, métriques SaaS)',
    'Multi-établissements & food courts',
    'Réservations avec acompte déductible',
    'Pré-commandes liées aux réservations',
    'Commandes groupées (plusieurs participants)',
    'Programme fidélité & badges gamification (Pro)',
    'Campagnes WhatsApp/SMS ciblées RFM (Pro)',
    'NPS & enquêtes satisfaction automatiques',
    'Studio personnalisation menu (3 modes preview)',
    '15 layouts premium (Galerie, Magazine, Néon, Bio...)',
    'Conformité fiscale SYSCOHADA & DGI multi-pays',
    'Tickets fiscaux séquentiels immuables',
    'TVA dynamique (CI 18%, CM 19.25%, GH 15%, MA 20%)',
    'Impression thermique ESC/POS (cuisine + caisse)',
    'PWA installable mobile/tablette',
    'Mode hors-ligne (KDS + serveur, IndexedDB)',
    'Notifications Web Push + WhatsApp + SMS',
    'Multi-langues (FR, EN, AR, Wolof, Dyula)',
    'RGPD : export données + anonymisation 1-clic',
    'Intégrations POS (Lightspeed, Square, Odoo) (Enterprise)',
    'Opera PMS hôtel (facturation chambre) (Enterprise)',
    'Google Maps & Instagram Graph API',
    'Audit trail complet & logs immutables',
    'IA Proph3t (recommandations menu, alertes stock)',
    'API REST pour intégrations sur mesure (Enterprise)',
    'SSO Atlas Studio inclus',
    'Support email',
    'Support prioritaire & account manager (Enterprise)',
    'Onboarding accompagné 1 session (Pro)',
    'Formation incluse 2 sessions/an (Enterprise)'
  ],
  ARRAY['Restauration', 'Hôtellerie', 'Paiement', 'POS'],
  '{"Starter": 25000, "Pro": 75000, "Enterprise": 200000}'::jsonb,
  'mois',
  '#C9A84C',
  'utensils',
  ARRAY[
    'Mobile Money natif',
    '15 layouts premium',
    'Conforme OHADA + DGI'
  ],
  'https://tablesmart.atlas-studio.org',
  'available',
  10
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  type = EXCLUDED.type,
  tagline = EXCLUDED.tagline,
  description = EXCLUDED.description,
  features = EXCLUDED.features,
  categories = EXCLUDED.categories,
  pricing = EXCLUDED.pricing,
  pricing_period = EXCLUDED.pricing_period,
  color = EXCLUDED.color,
  icon = EXCLUDED.icon,
  highlights = EXCLUDED.highlights,
  external_url = EXCLUDED.external_url,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();
