import { useState, useEffect, useRef } from "react";
import { Database, Plus, Trash2, Upload, FileText, Loader2 } from "lucide-react";
import { supabase } from "../../lib/supabase";
import { AdminTable } from "../components/AdminTable";
import { AdminPageHeader } from "../components/AdminPageHeader";
import { AdminSearch } from "../components/AdminSearch";
import { AdminFilterPills } from "../components/AdminFilterPills";
import { AdminButton } from "../components/AdminButton";
import { AdminModal } from "../components/AdminModal";
import { AdminConfirmDialog } from "../components/AdminConfirmDialog";
import { AdminFormField, ADMIN_INPUT_CLASS } from "../components/AdminFormField";
import { useToast } from "../contexts/ToastContext";
import { formatSupabaseError } from "../../lib/errorMessages";

interface KnowledgeChunk {
  id: string;
  source_type: string;
  title: string;
  content: string;
  metadata: Record<string, any>;
  chunk_index: number;
  source_id: string | null;
  created_at: string;
}

const SOURCE_LABELS: Record<string, string> = {
  cdc: "Cahier des charges",
  ohada_rule: "Règle OHADA",
  uemoa_regulation: "Réglementation UEMOA",
  cemac_regulation: "Réglementation CEMAC",
  fiscal_ci: "Fiscalité CI",
  product_doc: "Documentation produit",
  business_rule: "Règle métier",
  faq: "FAQ",
  decision_log: "Historique décisions",
};

const SOURCE_COLORS: Record<string, string> = {
  cdc: "bg-blue-500/20 text-blue-400",
  ohada_rule: "bg-emerald-500/20 text-emerald-400",
  uemoa_regulation: "bg-cyan-500/20 text-cyan-400",
  cemac_regulation: "bg-teal-500/20 text-teal-400",
  fiscal_ci: "bg-amber-500/20 text-amber-400",
  product_doc: "bg-purple-500/20 text-purple-400",
  business_rule: "bg-indigo-500/20 text-indigo-400",
  faq: "bg-orange-500/20 text-orange-400",
  decision_log: "bg-rose-500/20 text-rose-400",
};

export default function Proph3tKnowledgePage() {
  const { success, error: showError } = useToast();
  const [chunks, setChunks] = useState<KnowledgeChunk[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");
  const [showUpload, setShowUpload] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [uploadForm, setUploadForm] = useState({ title: "", source_type: "product_doc", content: "" });
  const [detailChunk, setDetailChunk] = useState<KnowledgeChunk | null>(null);
  const [confirmDialog, setConfirmDialog] = useState<{ open: boolean; title: string; message: string; onConfirm: () => void }>({ open: false, title: "", message: "", onConfirm: () => {} });
  const fileRef = useRef<HTMLInputElement>(null);

  const fetchChunks = async () => {
    const { data } = await supabase.from("proph3t_knowledge").select("*").order("created_at", { ascending: false });
    setChunks(data as KnowledgeChunk[] || []);
    setLoading(false);
  };

  useEffect(() => { fetchChunks(); }, []);

  const filtered = chunks.filter(c => {
    if (typeFilter !== "all" && c.source_type !== typeFilter) return false;
    if (search && !c.title.toLowerCase().includes(search.toLowerCase()) && !c.content.toLowerCase().includes(search.toLowerCase())) return false;
    return true;
  });

  // Group by source_id to show document-level view
  const uniqueSources = [...new Set(chunks.map(c => c.source_id || c.id))];
  const documentCount = uniqueSources.length;

  const handleUpload = async () => {
    if (!uploadForm.title || !uploadForm.content) return;
    setUploading(true);

    // Split content into chunks of ~500 words
    const words = uploadForm.content.split(/\s+/);
    const chunkSize = 500;
    const overlap = 50;
    const textChunks: string[] = [];

    for (let i = 0; i < words.length; i += chunkSize - overlap) {
      textChunks.push(words.slice(i, i + chunkSize).join(" "));
    }

    const sourceId = `${uploadForm.source_type}_${uploadForm.title.toLowerCase().replace(/\s+/g, "_")}`;

    // Delete existing chunks with same source_id (re-index)
    await supabase.from("proph3t_knowledge").delete().eq("source_id", sourceId);

    // Insert chunks (without embeddings — those will be generated by Edge Function)
    const rows = textChunks.map((content, i) => ({
      source_type: uploadForm.source_type,
      title: uploadForm.title,
      content,
      chunk_index: i,
      source_id: sourceId,
      metadata: { total_chunks: textChunks.length, word_count: content.split(/\s+/).length },
    }));

    const { error } = await supabase.from("proph3t_knowledge").insert(rows);
    setUploading(false);

    if (error) showError(formatSupabaseError(error));
    else {
      success(`${textChunks.length} chunk(s) indexés pour "${uploadForm.title}"`);
      setShowUpload(false);
      setUploadForm({ title: "", source_type: "product_doc", content: "" });
      fetchChunks();
    }
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const text = await file.text();
    setUploadForm(prev => ({
      ...prev,
      title: prev.title || file.name.replace(/\.[^/.]+$/, ""),
      content: text,
    }));
    if (fileRef.current) fileRef.current.value = "";
  };

  const deleteSource = (sourceId: string, title: string) => {
    setConfirmDialog({
      open: true, title: "Supprimer ce document ?",
      message: `Tous les chunks de "${title}" seront supprimés de la base de connaissances.`,
      onConfirm: async () => {
        await supabase.from("proph3t_knowledge").delete().eq("source_id", sourceId);
        setConfirmDialog(prev => ({ ...prev, open: false }));
        success("Document supprimé de la base de connaissances");
        fetchChunks();
      },
    });
  };

  const bulkDelete = (ids: string[]) => {
    setConfirmDialog({
      open: true, title: `Supprimer ${ids.length} chunk(s) ?`, message: "Cette action est irréversible.",
      onConfirm: async () => {
        await supabase.from("proph3t_knowledge").delete().in("id", ids);
        setConfirmDialog(prev => ({ ...prev, open: false }));
        success(`${ids.length} chunk(s) supprimé(s)`);
        fetchChunks();
      },
    });
  };

  const typeFilters = [
    { label: "Tous", value: "all", count: chunks.length },
    ...Object.entries(SOURCE_LABELS).map(([key, label]) => ({
      label, value: key, count: chunks.filter(c => c.source_type === key).length,
    })).filter(f => f.count > 0),
  ];

  return (
    <div>
      <AdminPageHeader title="Base de connaissances Proph3t (RAG)" subtitle={`${chunks.length} chunks — ${documentCount} documents indexés`}>
        <AdminButton icon={Plus} onClick={() => setShowUpload(true)}>Indexer un document</AdminButton>
      </AdminPageHeader>

      <div className="flex items-center gap-4 mb-6 flex-wrap">
        <AdminFilterPills filters={typeFilters} value={typeFilter} onChange={setTypeFilter} />
        <AdminSearch value={search} onChange={setSearch} placeholder="Rechercher dans la base..." />
      </div>

      <AdminTable
        keyExtractor={(r: KnowledgeChunk) => r.id}
        loading={loading}
        selectable
        bulkActions={[{ label: "Supprimer", onClick: bulkDelete, variant: "danger" }]}
        emptyMessage="Aucun document indexé"
        emptyIcon={<Database size={32} />}
        onRowClick={setDetailChunk}
        columns={[
          { key: "source_type", label: "Type", render: (r: KnowledgeChunk) => (
            <span className={`inline-flex px-2 py-0.5 rounded-full text-[10px] font-semibold ${SOURCE_COLORS[r.source_type] || "bg-neutral-500/20 text-neutral-400"}`}>
              {SOURCE_LABELS[r.source_type] || r.source_type}
            </span>
          )},
          { key: "title", label: "Document", sortable: true, render: (r: KnowledgeChunk) => (
            <div>
              <div className="text-neutral-text dark:text-admin-text text-[13px] font-medium">{r.title}</div>
              <div className="text-neutral-muted dark:text-admin-muted text-[11px]">Chunk {r.chunk_index + 1} · {r.content.split(/\s+/).length} mots</div>
            </div>
          )},
          { key: "content", label: "Extrait", render: (r: KnowledgeChunk) => (
            <span className="text-neutral-muted dark:text-admin-muted text-[11px] truncate block max-w-[250px]">{r.content.slice(0, 100)}...</span>
          )},
          { key: "created_at", label: "Indexé le", sortable: true, render: (r: KnowledgeChunk) => (
            <span className="text-[12px] text-neutral-muted dark:text-admin-muted">{new Date(r.created_at).toLocaleDateString("fr-FR", { day: "2-digit", month: "short" })}</span>
          )},
          { key: "actions", label: "", render: (r: KnowledgeChunk) => (
            <button onClick={e => { e.stopPropagation(); deleteSource(r.source_id || r.id, r.title); }}
              className="p-1.5 rounded hover:bg-red-50 dark:hover:bg-red-500/10 text-neutral-muted dark:text-admin-muted hover:text-red-500 transition-colors">
              <Trash2 size={14} />
            </button>
          )},
        ]}
        data={filtered}
      />

      {/* Upload modal */}
      <AdminModal open={showUpload} onClose={() => setShowUpload(false)} title="Indexer un document" size="xl"
        subtitle="Le contenu sera découpé en chunks et indexé pour la recherche sémantique RAG"
        footer={<AdminButton onClick={handleUpload} loading={uploading} disabled={!uploadForm.title || !uploadForm.content}>
          {uploading ? "Indexation..." : "Indexer le document"}
        </AdminButton>}>
        <div className="space-y-4">
          <AdminFormField label="Titre du document">
            <input value={uploadForm.title} onChange={e => setUploadForm(p => ({ ...p, title: e.target.value }))} placeholder="ex: SYSCOHADA Révisé — Plan Comptable" className={ADMIN_INPUT_CLASS} />
          </AdminFormField>

          <AdminFormField label="Type de source">
            <select value={uploadForm.source_type} onChange={e => setUploadForm(p => ({ ...p, source_type: e.target.value }))} className={ADMIN_INPUT_CLASS}>
              {Object.entries(SOURCE_LABELS).map(([key, label]) => (
                <option key={key} value={key}>{label}</option>
              ))}
            </select>
          </AdminFormField>

          <AdminFormField label="Contenu">
            <div className="space-y-2">
              <input ref={fileRef} type="file" accept=".txt,.md,.csv" onChange={handleFileUpload} className="hidden" />
              <button onClick={() => fileRef.current?.click()}
                className="inline-flex items-center gap-2 px-4 py-2 border border-warm-border dark:border-admin-surface-alt rounded-lg text-[12px] font-medium text-neutral-body dark:text-admin-text hover:border-gold/40 dark:hover:border-admin-accent/40 transition-colors">
                <Upload size={14} /> Charger un fichier (.txt, .md)
              </button>
              <textarea value={uploadForm.content} onChange={e => setUploadForm(p => ({ ...p, content: e.target.value }))} rows={15}
                className={`${ADMIN_INPUT_CLASS} resize-y font-mono text-[12px] leading-relaxed`}
                placeholder="Collez le contenu du document ici ou chargez un fichier..." />
              {uploadForm.content && (
                <div className="text-neutral-muted dark:text-admin-muted text-[11px]">
                  {uploadForm.content.split(/\s+/).length} mots · sera découpé en ~{Math.ceil(uploadForm.content.split(/\s+/).length / 450)} chunks
                </div>
              )}
            </div>
          </AdminFormField>
        </div>
      </AdminModal>

      {/* Detail modal */}
      <AdminModal open={!!detailChunk} onClose={() => setDetailChunk(null)} title={detailChunk?.title || ""} size="lg"
        subtitle={detailChunk ? `${SOURCE_LABELS[detailChunk.source_type] || detailChunk.source_type} · Chunk ${detailChunk.chunk_index + 1}` : undefined}>
        {detailChunk && (
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <span className={`inline-flex px-2.5 py-1 rounded-full text-[11px] font-semibold ${SOURCE_COLORS[detailChunk.source_type] || ""}`}>
                {SOURCE_LABELS[detailChunk.source_type] || detailChunk.source_type}
              </span>
              <span className="text-neutral-muted dark:text-admin-muted text-[12px]">{detailChunk.content.split(/\s+/).length} mots</span>
            </div>
            <div>
              <div className="text-neutral-muted dark:text-admin-muted text-[11px] font-semibold uppercase mb-1">Contenu</div>
              <div className="text-neutral-text dark:text-admin-text text-[13px] whitespace-pre-wrap bg-warm-bg dark:bg-admin-surface-alt p-4 rounded-lg leading-relaxed max-h-[400px] overflow-y-auto">
                {detailChunk.content}
              </div>
            </div>
            {detailChunk.metadata && Object.keys(detailChunk.metadata).length > 0 && (
              <div>
                <div className="text-neutral-muted dark:text-admin-muted text-[11px] font-semibold uppercase mb-1">Metadata</div>
                <pre className="bg-warm-bg dark:bg-admin-surface-alt rounded-lg p-4 text-[12px] font-mono text-neutral-text dark:text-admin-text whitespace-pre-wrap">
                  {JSON.stringify(detailChunk.metadata, null, 2)}
                </pre>
              </div>
            )}
            <div className="text-[12px] text-neutral-muted dark:text-admin-muted">
              Source ID : <span className="font-mono">{detailChunk.source_id || "—"}</span> · Indexé le {new Date(detailChunk.created_at).toLocaleString("fr-FR")}
            </div>
          </div>
        )}
      </AdminModal>

      <AdminConfirmDialog {...confirmDialog} onCancel={() => setConfirmDialog(prev => ({ ...prev, open: false }))} />
    </div>
  );
}
